/**
 * Type definitions for NOVALEAP Database Models
 * 
 * These types are automatically generated by Prisma from the schema,
 * but we also define custom types and interfaces for API responses.
 */

// Service Types
export interface Service {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  price: number;
  duration: number;
  category: string;
  icon: string | null;
  image: string | null;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface ServiceWithAppointments extends Service {
  appointments: Appointment[];
}

// Appointment Types
export enum AppointmentStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELED = "CANCELED",
  NO_SHOW = "NO_SHOW",
}

export interface Appointment {
  id: string;
  serviceId: string;
  service?: Service;
  clientName: string;
  clientEmail: string;
  clientPhone: string | null;
  status: AppointmentStatus;
  scheduledAt: Date;
  notes: string | null;
  canceledAt: Date | null;
  cancelReason: string | null;
  createdAt: Date;
  updatedAt: Date;
}

// API Response Types
export interface ApiResponse<T> {
  status: "success" | "error";
  data?: T;
  message?: string;
  errors?: Record<string, string[]>;
}

export interface PaginatedResponse<T> extends ApiResponse<T[]> {
  pagination: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}

// User Types
export enum UserRole {
  CLIENT = "CLIENT",
  STAFF = "STAFF",
  ADMIN = "ADMIN",
}

export interface User {
  id: string;
  email: string;
  name: string | null;
  role: UserRole;
  createdAt: Date;
  updatedAt: Date;
}
